# Generated by Django 6.0.3 on 2026-03-26 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaoGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chi_phi_thiet_ke', models.DecimalField(decimal_places=0, max_digits=12)),
                ('phi_van_chuyen', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tong_tien', models.DecimalField(decimal_places=0, max_digits=12)),
                ('anh_mau_de_xuat', models.ImageField(blank=True, null=True, upload_to='baogia/samples/')),
                ('noi_dung_tu_van', models.TextField()),
                ('trang_thai', models.CharField(default='ChoDuyet', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dang_nhap', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mat_khau', models.CharField(max_length=128)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('vai_tro', models.CharField(choices=[('KHACH_HANG', 'Khách hàng'), ('TIEM_HOA', 'Tiệm hoa'), ('ADMIN', 'Quản trị viên')], max_length=20)),
                ('trang_thai', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhienChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YeuCauThietKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dip_su_dung', models.CharField(max_length=255)),
                ('ngan_sach', models.DecimalField(decimal_places=0, max_digits=12)),
                ('mau_sac', models.CharField(max_length=100)),
                ('thoi_gian_hoan_thanh', models.DateTimeField()),
                ('phong_cach', models.CharField(max_length=255)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('dia_chi_giao_hang', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateTimeField(auto_now_add=True)),
                ('anh_san_pham_thuc_te', models.ImageField(blank=True, null=True, upload_to='orders/actual/')),
                ('trang_thai_don_hang', models.CharField(default='DangXuLy', max_length=50)),
                ('ngay_giao_du_kien', models.DateTimeField()),
                ('bao_gia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.baogia')),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.taikhoan')),
                ('ten_khach_hang', models.CharField(max_length=255)),
                ('dia_chi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TiemHoa',
            fields=[
                ('tai_khoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.taikhoan')),
                ('ten_tiem_hoa', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ma_so_thue', models.CharField(blank=True, max_length=50, null=True)),
                ('hinh_anh_san_pham', models.ImageField(blank=True, null=True, upload_to='tiem_hoa/products/')),
                ('logo_tiem_hoa', models.ImageField(blank=True, null=True, upload_to='tiem_hoa/logos/')),
                ('trang_thai_duyet', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noi_dung', models.TextField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('nguoi_gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taikhoan')),
                ('phien_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.phienchat')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_tai_khoan', models.CharField(max_length=50)),
                ('ten_ngan_hang', models.CharField(max_length=100)),
                ('ten_chu_tai_khoan', models.CharField(max_length=255)),
                ('qr_tiem_hoa', models.ImageField(blank=True, null=True, upload_to='payments/qr/')),
                ('tong_tien', models.DecimalField(decimal_places=0, max_digits=12)),
                ('hinh_anh_bien_lai', models.ImageField(upload_to='payments/receipts/')),
                ('don_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.donhang')),
            ],
        ),
        migrations.AddField(
            model_name='baogia',
            name='yeu_cau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.yeucauthietke'),
        ),
        migrations.AddField(
            model_name='yeucauthietke',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.khachhang'),
        ),
        migrations.AddField(
            model_name='phienchat',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.khachhang'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='khach_hang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.khachhang'),
        ),
        migrations.AddField(
            model_name='yeucauthietke',
            name='tiem_hoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiemhoa'),
        ),
        migrations.AddField(
            model_name='phienchat',
            name='tiem_hoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiemhoa'),
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.IntegerField(default=5)),
                ('noi_dung', models.TextField()),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True)),
                ('don_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.donhang')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.khachhang')),
                ('tiem_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiemhoa')),
            ],
        ),
    ]
